development:
  adapter: postgresql
  database: poi_development_db
  pool: 5
  timeout: 5000
  host: localhost
  
test:
  adapter: postgresql
  database: poi_test_db
  pool: 5
  timeout: 5000
  host: localhost
  
production:
  adapter: postgresql
  host: ec2-54-225-103-9.compute-1.amazonaws.com
  database: d89q0a4fpl7o5t
  username: mozulnvrlpzjzd
  password: 3hmP-pxBdz_DjOg73CmGBscj6Q
  pool: 5
  timeout: 5000